### ISSUE TITLE
Question about depth

### ISSUE THREAD

**Issue by xiaoerlaigeid** [chledowski/dbtpnet#1]
Thanks for your work. I have one question about your network input. As you mentioned in the paper, the channel should be 30. I wonder your provided code the input channel is 1. Maybe I missed something?

**Comment by chledowski** [comment]
Hi! @xiaoerlaigeid! 

There should be 1 channel for color (so greyscale instead of RGB), but 30 for the depth dimension (the number of slices of the 3D image).

Hope this helps!

**Comment by xiaoerlaigeid** [comment]
Hi,thanks your reply, I mean the network model input should be 30 channel ? right ? but you release code input is just 1 channel

**Comment by chledowski** [comment]
1 is just for RGB.
30 is for depth.
In 3D convolutions you have one extra dimension - depth. 

So, the number of channels is really 1, but the depth is 30. It's a matter of definition :)

**Comment by xiaoerlaigeid** [comment]
Oh, thanks, I get your means. At first I thought you just use the 2D CNN, the channel layer is the 30. Actually, you use the 3D layer, the channel layer is 1 and depth is 30. Thanks !

**Comment by chledowski** [comment]
You're welcome!
